trigger:
  branches:
    include:
      - master
pool:
  vmImage: "ubuntu-latest"

variables:
  - group: ess-dev-env
  - name: containerRegistry
    value: acress.azurecr.io
  - name: tag
    value: "$(Build.BuildId)"
  - name: imageRepository
    value: ec-ess.dev
  - name: dockerRegistryServiceConnection
    value: ess-acr-connection #view it on service connection
  - name: kubeNamespace
    value: apipython #the namespace inside the kubernetes cluster
  - name: deploymentName
    value: deployment-apipython
  - name: containerName
    value: app-apipython
steps:
  - task: Docker@2
    displayName: Build and push image to registry
    inputs:
      command: buildAndPush
      repository: $(imageRepository)
      containerRegistry: $(dockerRegistryServiceConnection)
      Dockerfile: Dockerfile
      buildContext: ./
      tags: |
        $(tag)
  - task: Kubernetes@1
    displayName: dev - deployment new image of schedule to AKS cluster
    inputs:
      connectionType: "Kubernetes Service Connection"
      kubernetesServiceEndpoint: "ess-develop-env-connection"
      namespace: "$(kubeNamespace)"
      command: "set"
      arguments: "image deployment/$(deploymentName) $(containerName)=$(containerRegistry)/$(imageRepository):$(tag)"
      secretType: "dockerRegistry"
      containerRegistryType: "Container Registry"
      dockerRegistryEndpoint: "$(dockerRegistryServiceConnection)"
